title: Justin Wu's Homepage
page-top-title: Justin Wu
top-section-bg-text: Electronic Engineering
home-subtitle: Justin Wu&ensp;|&ensp;吴憬泰
copyright-text: '&copy; Justin Wu 2024-2025. All Rights Reserved.'
